### ISSUE TITLE
Install Script Fails to Complete on Debian 8.0/8.5

### ISSUE THREAD

**Issue by nathanielban** [cdr-stats/cdr-stats#43]
I've been trying for the past several days to get CDR Stats installed, there appears to be a bug in the install script. From what I can tell from reading the last error I saw it appears to be Django related:

![Screenshot of Error](https://i.imgur.com/VdHR5BP.png)

The main webroot (Port 80) is staged correctly but the script itself is not available on port 8008:

![NGINX Shows a 404 because the upstream proxy isnt running](https://i.imgur.com/5MmF5PI.png)

Does anyone have any ideas?

**Comment by gled-rs** [comment]
can reproduce the same on a fresh installed jessie.

the install script also seems to forget to pip install importlib during setup, and install gunicorn itself.

Did not went further debugging the long install script.

**Comment by gled-rs** [comment]
PS: the script also fails on a debian 7 ( wheezie )

**Comment by areski** [comment]
This has been solved now https://github.com/cdr-stats/cdr-stats/commit/2133d0a1dbbd78d3b69fad3a51d574b705703d0c

**Comment by nathanielban** [comment]
It is still broken, theres a new error this time:

![New Error](https://i.imgur.com/1SRJVgk.png)

**Comment by gled-rs** [comment]
Confirmed,  PR #44 solves the issue.
